### ISSUE TITLE
Failed to load namespaces

### ISSUE THREAD

**Issue by heartofrevel** [njust/kubelog#8]
Kubelog doesn't load namespaces when opened.
![image](https://github.com/njust/kubelog/assets/5503684/2e8b5b02-b555-4a22-94fa-3b40c98e186f)

**Comment by njust** [comment]
Hi, please check the logs for more details on the error:

Linux:
$HOME/.local/share/kubelog/logs/

macOS
$HOME/Library/Application Support/kubelog/logs/

Windows:
%appdata%\kubelog\data\logs

**Comment by msaraac** [comment]
Failed to load namespaces: auth error: unable to run auth exec: No such file or directory (os error 2)

**Comment by njust** [comment]
The issue is, that the credential plugin cannot be loaded. I assume that you are on macOS and kubectl works as expected? If so, can you try to set the full path of your credential plugin in your kube config like below (the command) and check if kubelog can load the namespaces:

```yaml
- name: arn:aws:eks:eu-central-1:435496144405:cluster/test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - test
      - --output
      - json
      command: /usr/local/aws-cli/aws
```

You should have a similar entry in your kube config, only modify the command so that it is a full-qualified path.
